In [4]:
import pandas as pd
import numpy as np
import pickle
import matplotlib. pyplot as plt
%matplotlib inline
import seaborn as sns
import sklearn
from sklearn . tree import DecisionTreeClassifier
from sklearn . ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn . neighbors import KNeighborsClassifier
from sklearn . model_selection import RandomizedSearchCV
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score


In [5]:
dataset= pd.read_csv("flightdata.csv")

In [6]:
dataset.head()

YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK UNIQUE_CARRIER TAIL_NUM  \
0  2016        1      1             1            5             DL   N836DN   
1  2016        1      1             1            5             DL   N964DN   
2  2016        1      1             1            5             DL   N813DN   
3  2016        1      1             1            5             DL   N587NW   
4  2016        1      1             1            5             DL   N836DN   

   FL_NUM  ORIGIN_AIRPORT_ID ORIGIN  ...  CRS_ARR_TIME ARR_TIME  ARR_DELAY  \
0    1399              10397    ATL  ...          2143   2102.0      -41.0   
1    1476              11433    DTW  ...          1435   1439.0        4.0   
2    1597              10397    ATL  ...          1215   1142.0      -33.0   
3    1768              14747    SEA  ...          1335   1345.0       10.0   
4    1823              14747    SEA  ...           607    615.0        8.0   

   ARR_DEL15  CANCELLED  DIVERTED  CRS_ELAPSED_TIME  ACTUAL_ELAPSED_TIME  \
0        0.0        0.0       0.0             338.0                295.0   
1        0.0        0.0       0.0             110.0                115.0   
2        0.0        0.0       0.0             335.0                300.0   
3        0.0        0.0       0.0             196.0                205.0   
4        0.0        0.0       0.0             247.0                259.0   

   DISTANCE  Unnamed: 25  
0    2182.0          NaN  
1     528.0          NaN  
2    2182.0          NaN  
3    1399.0          NaN  
4    1927.0          NaN  

[5 rows x 26 columns]

In [77]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11231 entries, 0 to 11230
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   YEAR                 11231 non-null  int64  
 1   QUARTER              11231 non-null  int64  
 2   MONTH                11231 non-null  int64  
 3   DAY_OF_MONTH         11231 non-null  int64  
 4   DAY_OF_WEEK          11231 non-null  int64  
 5   UNIQUE_CARRIER       11231 non-null  object 
 6   TAIL_NUM             11231 non-null  object 
 7   FL_NUM               11231 non-null  int64  
 8   ORIGIN_AIRPORT_ID    11231 non-null  int64  
 9   ORIGIN               11231 non-null  object 
 10  DEST_AIRPORT_ID      11231 non-null  int64  
 11  DEST                 11231 non-null  object 
 12  CRS_DEP_TIME         11231 non-null  int64  
 13  DEP_TIME             11124 non-null  float64
 14  DEP_DELAY            11124 non-null  float64
 15  DEP_DEL15            11124 non-null 

In [78]:
dataset = dataset.drop('Unnamed: 25',axis=1)
dataset.isnull().sum()

YEAR                     0
QUARTER                  0
MONTH                    0
DAY_OF_MONTH             0
DAY_OF_WEEK              0
UNIQUE_CARRIER           0
TAIL_NUM                 0
FL_NUM                   0
ORIGIN_AIRPORT_ID        0
ORIGIN                   0
DEST_AIRPORT_ID          0
DEST                     0
CRS_DEP_TIME             0
DEP_TIME               107
DEP_DELAY              107
DEP_DEL15              107
CRS_ARR_TIME             0
ARR_TIME               115
ARR_DELAY              188
ARR_DEL15              188
CANCELLED                0
DIVERTED                 0
CRS_ELAPSED_TIME         0
ACTUAL_ELAPSED_TIME    188
DISTANCE                 0
dtype: int64

In [79]:
dataset = dataset[["FL_NUM", "MONTH", "DAY_OF_MONTH", "DAY_OF_WEEK", "ORIGIN", "DEST", "CRS_ARR_TIME", "DEP_DEL15", "ARR_DEL15"]]
dataset.isnull().sum()

FL_NUM            0
MONTH             0
DAY_OF_MONTH      0
DAY_OF_WEEK       0
ORIGIN            0
DEST              0
CRS_ARR_TIME      0
DEP_DEL15       107
ARR_DEL15       188
dtype: int64

In [80]:
dataset[dataset.isnull().any(axis=1)].head(10)

FL_NUM  MONTH  DAY_OF_MONTH  DAY_OF_WEEK ORIGIN DEST  CRS_ARR_TIME  \
177    2834      1             9            6    MSP  SEA           852   
179      86      1            10            7    MSP  DTW          1632   
184     557      1            10            7    MSP  DTW           912   
210    1096      1            10            7    DTW  MSP          1303   
478    1542      1            22            5    SEA  JFK           723   
481    1795      1            22            5    ATL  JFK          2014   
491    2312      1            22            5    MSP  JFK          2149   
499     423      1            23            6    JFK  ATL          1600   
500     425      1            23            6    JFK  ATL          1827   
501     427      1            23            6    JFK  SEA          1053   

     DEP_DEL15  ARR_DEL15  
177        0.0        NaN  
179        NaN        NaN  
184        0.0        NaN  
210        NaN        NaN  
478        NaN        NaN  
481        NaN        NaN  
491        NaN        NaN  
499        NaN        NaN  
500        NaN        NaN  
501        NaN        NaN

In [81]:
dataset['DEP_DEL15'].mode()

0    0.0
Name: DEP_DEL15, dtype: float64

In [82]:
dataset=dataset.fillna({'ARR_DEL15':1})
dataset=dataset.fillna({'DEP_DEL15':0})
dataset.iloc[177:185]

FL_NUM  MONTH  DAY_OF_MONTH  DAY_OF_WEEK ORIGIN DEST  CRS_ARR_TIME  \
177    2834      1             9            6    MSP  SEA           852   
178    2839      1             9            6    DTW  JFK          1724   
179      86      1            10            7    MSP  DTW          1632   
180      87      1            10            7    DTW  MSP          1649   
181     423      1            10            7    JFK  ATL          1600   
182     440      1            10            7    JFK  ATL           849   
183     485      1            10            7    JFK  SEA          1945   
184     557      1            10            7    MSP  DTW           912   

     DEP_DEL15  ARR_DEL15  
177        0.0        1.0  
178        0.0        0.0  
179        0.0        1.0  
180        1.0        0.0  
181        0.0        0.0  
182        0.0        0.0  
183        1.0        0.0  
184        0.0        1.0

In [83]:
import math

for index,row in dataset.iterrows():
    dataset.loc[index, 'CRS_ARR_TIME']=math.floor(row['CRS_ARR_TIME']/ 100)
dataset.head()

FL_NUM  MONTH  DAY_OF_MONTH  DAY_OF_WEEK ORIGIN DEST  CRS_ARR_TIME  \
0    1399      1             1            5    ATL  SEA            21   
1    1476      1             1            5    DTW  MSP            14   
2    1597      1             1            5    ATL  SEA            12   
3    1768      1             1            5    SEA  MSP            13   
4    1823      1             1            5    SEA  DTW             6   

   DEP_DEL15  ARR_DEL15  
0        0.0        0.0  
1        0.0        0.0  
2        0.0        0.0  
3        0.0        0.0  
4        0.0        0.0

In [84]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['DEST'] = le.fit_transform(dataset["DEST"])
dataset['ORIGIN'] = le.fit_transform(dataset['ORIGIN'])

In [85]:
dataset.head(5)

FL_NUM  MONTH  DAY_OF_MONTH  DAY_OF_WEEK  ORIGIN  DEST  CRS_ARR_TIME  \
0    1399      1             1            5       0     4            21   
1    1476      1             1            5       1     3            14   
2    1597      1             1            5       0     4            12   
3    1768      1             1            5       4     3            13   
4    1823      1             1            5       4     1             6   

   DEP_DEL15  ARR_DEL15  
0        0.0        0.0  
1        0.0        0.0  
2        0.0        0.0  
3        0.0        0.0  
4        0.0        0.0

In [86]:
dataset['ORIGIN'].unique()

array([0, 1, 4, 3, 2])

In [87]:
dataset = pd.get_dummies(dataset, columns=['ORIGIN', 'DEST'])
dataset.head()

FL_NUM  MONTH  DAY_OF_MONTH  DAY_OF_WEEK  CRS_ARR_TIME  DEP_DEL15  \
0    1399      1             1            5            21        0.0   
1    1476      1             1            5            14        0.0   
2    1597      1             1            5            12        0.0   
3    1768      1             1            5            13        0.0   
4    1823      1             1            5             6        0.0   

   ARR_DEL15  ORIGIN_0  ORIGIN_1  ORIGIN_2  ORIGIN_3  ORIGIN_4  DEST_0  \
0        0.0         1         0         0         0         0       0   
1        0.0         0         1         0         0         0       0   
2        0.0         1         0         0         0         0       0   
3        0.0         0         0         0         0         1       0   
4        0.0         0         0         0         0         1       0   

   DEST_1  DEST_2  DEST_3  DEST_4  
0       0       0       0       1  
1       0       0       1       0  
2       0       0       0       1  
3       0       0       1       0  
4       1       0       0       0

In [88]:
x = dataset.iloc[:, 0:8].values
y = dataset.iloc[:, 8:9].values

In [89]:
x

array([[1.399e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [1.476e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.597e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       ...,
       [1.823e+03, 1.200e+01, 3.000e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.901e+03, 1.200e+01, 3.000e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00],
       [2.005e+03, 1.200e+01, 3.000e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00]])

In [90]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder()
z=oh.fit_transform(x[:,4:5]).toarray()
t=oh.fit_transform(x[:,5:6]).toarray()

In [91]:
z

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [92]:
t

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [93]:
x=np.delete(x,[4,5],axis=1)

In [94]:
dataset.describe()

FL_NUM         MONTH  DAY_OF_MONTH   DAY_OF_WEEK  CRS_ARR_TIME  \
count  11231.000000  11231.000000  11231.000000  11231.000000  11231.000000   
mean    1334.325617      6.628973     15.790758      3.960199     15.067314   
std      811.875227      3.354678      8.782056      1.995257      5.023534   
min        7.000000      1.000000      1.000000      1.000000      0.000000   
25%      624.000000      4.000000      8.000000      2.000000     11.000000   
50%     1267.000000      7.000000     16.000000      4.000000     15.000000   
75%     2032.000000      9.000000     23.000000      6.000000     19.000000   
max     2853.000000     12.000000     31.000000      7.000000     23.000000   

          DEP_DEL15     ARR_DEL15      ORIGIN_0      ORIGIN_1      ORIGIN_2  \
count  11231.000000  11231.000000  11231.000000  11231.000000  11231.000000   
mean       0.141483      0.139168      0.276022      0.195975      0.122340   
std        0.348535      0.346138      0.447048      0.396967      0.327693   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      1.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

           ORIGIN_3      ORIGIN_4        DEST_0        DEST_1        DEST_2  \
count  11231.000000  11231.000000  11231.000000  11231.000000  11231.000000   
mean       0.225982      0.179681      0.286795      0.196866      0.116820   
std        0.418246      0.383939      0.452285      0.397648      0.321219   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      1.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

             DEST_3        DEST_4  
count  11231.000000  11231.000000  
mean       0.221975      0.177544  
std        0.415593      0.382146  
min        0.000000      0.000000  
25%        0.000000      0.000000  
50%        0.000000      0.000000  
75%        0.000000      0.000000  
max        1.000000      1.000000

In [95]:
sns.distplot(dataset.MONTH)

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_9020\321936831.py:1: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  sns.distplot(dataset.MONTH)


<Axes: xlabel='MONTH', ylabel='Density'>

In [96]:
sns.heatmap(dataset.corr())

<Axes: >

In [97]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [98]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(dataset.drop('ARR_DEL15', axis=1),dataset['ARR_DEL15'], test_size=0.2, random_state=0)

In [99]:
x_test.shape

(2247, 6)

In [100]:
x_train.shape

(8984, 6)

In [101]:
y_test.shape

(2247, 1)

In [102]:
y_train.shape

(8984, 1)

In [103]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [104]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state = 0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [105]:
decisiontree = classifier.predict(x_test)

In [106]:
decisiontree

array([1, 0, 0, ..., 1, 0, 0], dtype=uint8)

In [107]:
from sklearn.metrics import accuracy_score
desac = accuracy_score(y_test,decisiontree)

In [108]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10,criterion='entropy')

In [109]:
rfc.fit(x_train,y_train)

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_9020\4070307935.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(x_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10)

In [110]:
y_predict = rfc.predict(x_test)

In [37]:
import tensorflow.cloud as tfc 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

ModuleNotFoundError: No module named 'tensorflow'

In [31]:
classification = Sequential()
classification.add(Dense(30,activation='relu'))
classification.add(Dense(128,activation='relu'))
classification.add(Dense(64,activation='relu'))
classification.add(Dense(32,activation='relu'))
classification.add(Dense(1,activation='sigmoid'))

NameError: name 'Sequential' is not defined

In [32]:
from sklearn import model_selection
from sklearn.neural_network import MLPClassifier

In [13]:
    dfs = []
models = [
           ('RF', RandomForestClassifier()),
           ('DecisionTree',DecisionTreeClassifier()),
           ('ANN' ,MLPClassifier())
 ]
results = []
names = []
scoring = ['accuracy', 'precision_weighted' , 'recall_weighted ', 'f1_weighted', 'roc_auc']
target_names = ['no delay' , 'delay' ]
name, model in models:
    kfold = model_selection.kFold(n_splits=5, shuffle=True, random_state=90210)
    cv_results = model_selection.cross_validate(model, x_train, y_train, cv=kfold, scoring=scoring)
    clf = nodel. fit (x_train, y_train)
    y_pred = clf. predict(x_test)
    print(name)
    print(classification_report (y_test, y_pred, target_nanes=target_names))
    results.append(cv_results)
    names.append(name)
    this_df = pd.DataFrame (cv_results)
    this_df['model'] = name
    dfs. append(this_df)
final = pd.concat (dfs, ignore_index=True)
return final




SyntaxError: invalid syntax (2085658906.py, line 11)

In [5]:
# Randomforest Accuracy
print('Training accuracy: ',accuracy_score(y_train,y_predict_train))
print('Testing accuracy: ',accuracy_score(y_test,y_predict))

NameError: name 'accuracy_score' is not defined

In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict)
cm

NameError: name 'y_test' is not defined

In [22]:
parameters = {
                'n_estimators' : [1,20,30,55,68,74,90,120,115],
                'criterion' :['gini','entropy'],
                'max_features' : ["auto", "sqrt", "log2"],
                'mx_depth' : [2,5,8,10], 'verbose' : [1,2,3,4,6,8,9,10]
    
}

In [23]:
RCV = RandomizedSearchCV(estimator=rf,param_distributions=parmeters,cv=10,n_iter=4)

NameError: name 'RandomizedSearchCV' is not defined

In [25]:
RCV.fit(x_train,y_train)

NameError: name 'RCV' is not defined

In [24]:
from sklearn.metrics import accuracy_score,classification_report
score = accuracy_score(y_pred,y_test)
print('The accuracy for ANN model is: {}%'.format(score*100))

NameError: name 'y_pred' is not defined

In [18]:
import pickle
pickle.dump(RCV,open('flight.pkl','wb'))

NameError: name 'RCV' is not defined

In [11]:
from flask import Flask,request,render_template
import numpy as np
import pandas as pd
import pickle
import os

In [12]:
model = pickle.load(open('flight.pkl','rb'))
app = Flask(_name_)

FileNotFoundError: [Errno 2] No such file or directory: 'flight.pkl'